//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrosAsistencia
    {
        public System.Guid Id { get; set; }
        public System.Guid IdPersonal { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public byte[] Foto { get; set; }
        public string Movimiento { get; set; }
        public System.Guid IdHorario { get; set; }
    
        public virtual Personal Personal { get; set; }
    }
}
